arenaRankName = {
    "01": "Novice",
    "02": "Contender",
    "03": "Duelist",
    "04": "Berserker",
    "05": "Sage",
    "06": "Guardian",
    "07": "Titan",
    "08": "General",
    "09": "Master",
    "10": "Archfiend",
    "11": "Ascended",
    "12": "Celestial",
    "13": "Apollo",
    "14": "Phanes",
    "15": "Eurynomos",
    "16": "Emperor",
    "17": "Suppressor",
    "18": "Beam",
    "19": "Barrager",
    "20": "Heavenly Judge",
    "21": "Gleaming God",
    "22": "Slumber God",
    "23": "Original God",
    "24": "Darkstalker",
    "25": "Ouranos",
    "26": "Phoebus",
    "27": "Athena"
}
